name: 🔍 Transparency Issue
description: Request clarification or report lack of transparency
title: "[TRANSPARENCY]: "
labels: ["transparency", "documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Transparency Request
        
        Help us improve transparency by identifying areas that need better documentation,
        clarification, or more open communication.
        
  - type: dropdown
    id: type
    attributes:
      label: Type of Transparency Issue
      description: What kind of transparency improvement are you requesting?
      options:
        - Missing documentation
        - Unclear process
        - Insufficient communication
        - Hidden decision-making
        - Lack of attribution
        - Undocumented changes
        - Other
    validations:
      required: true
      
  - type: input
    id: area
    attributes:
      label: Area/Component
      description: Which area of the project does this relate to?
      placeholder: "e.g., Build process, API documentation, Release notes"
    validations:
      required: true
      
  - type: textarea
    id: current_state
    attributes:
      label: Current State
      description: What is currently unclear or lacking in transparency?
      placeholder: |
        Describe what exists now:
        - What information is missing?
        - What is unclear or confusing?
        - Where is documentation inadequate?
    validations:
      required: true
      
  - type: textarea
    id: desired_state
    attributes:
      label: Desired State
      description: What would good transparency look like here?
      placeholder: |
        Describe what you'd like to see:
        - What information should be available?
        - How should it be presented?
        - What level of detail is needed?
    validations:
      required: true
      
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why is this transparency important? Who needs this information?
      placeholder: |
        Explain:
        - Who needs this information?
        - How will it be used?
        - What decisions does it support?
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        Include:
        - Links to related discussions
        - Examples from other projects
        - Historical context
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this transparency improvement?
      options:
        - High - Blocking work or decisions
        - Medium - Important for ongoing work
        - Low - Nice to have
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: I have checked existing documentation
          required: true
        - label: I have searched for similar requests
          required: true
        - label: I am willing to help improve documentation
          required: false
